language: node_js
deploy:
  provider: netlify
  site: <https://kjk-blog-front.netlify.app>
  auth: <2nFheOjPNN_Lt3hP3wvGiR1sXpBnDSgZgiOo5x2O4SM>
  edge: true # opt in to dpl v2
# node_js:
#   - '4'
# env:
#   - CXX=g++-4.8
# addons:
#   apt:
#     sources:
#       - ubuntu-toolchain-r-test
#     packages:
#       - g++-4.8

